modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "LGPL 3.0 or Later"

[[mods]]
modId = "jarviscci"
version = "${version}"
displayName = "Jarvis Common Config Index"
authors = "Linnea Gr√§f"
description = '''
Common Config Index for Minecraft mods
'''
#logoFile = ""

[[dependencies.jarviscci]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jarviscci]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"
